"""create initial schema

Revision ID: 9b2dc2972123
Revises: 
Create Date: 2026-07-11 11:34:28.142412
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '9b2dc2972123'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('async_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result_type', sa.Text(), nullable=True),
    sa.Column('result_id', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_jobs_job_type'), 'async_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_async_jobs_status'), 'async_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_async_jobs_user_id'), 'async_jobs', ['user_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('input_type', sa.Text(), nullable=False),
    sa.Column('input_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('competencies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_index(op.f('ix_job_postings_user_id'), 'job_postings', ['user_id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_user_id', sa.Text(), nullable=False),
    sa.Column('provider_username', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_accounts_provider_user')
    )
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('portfolio_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_sources_source_type'), 'portfolio_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_portfolio_sources_status'), 'portfolio_sources', ['status'], unique=False)
    op.create_index(op.f('ix_portfolio_sources_user_id'), 'portfolio_sources', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_posting_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_limit', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_experiences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_competencies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_job_posting_id'), 'analysis_results', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    op.create_table('job_posting_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_posting_id', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posting_attachments_job_posting_id'), 'job_posting_attachments', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_job_posting_attachments_status'), 'job_posting_attachments', ['status'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_source_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_source_id'], ['portfolio_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_document_type'), 'source_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_source_documents_portfolio_source_id'), 'source_documents', ['portfolio_source_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('job_posting_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_job_posting_id'), 'evidences', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_evidences_project_id'), 'evidences', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidences_source_document_id'), 'evidences', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_evidences_source_type'), 'evidences', ['source_type'], unique=False)
    op.create_table('project_source_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=False),
    sa.Column('merge_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_source_links_project_id'), 'project_source_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_source_links_source_document_id'), 'project_source_links', ['source_document_id'], unique=False)
    op.create_table('recommended_projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_result_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_result_id', 'project_id', name='uq_recommended_projects_result_project')
    )
    op.create_index(op.f('ix_recommended_projects_analysis_result_id'), 'recommended_projects', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_recommended_projects_project_id'), 'recommended_projects', ['project_id'], unique=False)
    op.create_table('resume_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_posting_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_result_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_results_analysis_result_id'), 'resume_results', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_resume_results_job_posting_id'), 'resume_results', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_resume_results_user_id'), 'resume_results', ['user_id'], unique=False)
    op.create_table('project_suggestions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_result_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('estimated_duration', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_result_id'], ['resume_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_suggestions_resume_result_id'), 'project_suggestions', ['resume_result_id'], unique=False)
    op.create_table('recommendation_evidences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommended_project_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_project_id'], ['recommended_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommended_project_id', 'evidence_id', name='uq_recommendation_evidences_pair')
    )
    op.create_index(op.f('ix_recommendation_evidences_evidence_id'), 'recommendation_evidences', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_recommendation_evidences_recommended_project_id'), 'recommendation_evidences', ['recommended_project_id'], unique=False)
    op.create_table('resume_result_projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_result_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_result_id'], ['resume_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_result_id', 'project_id', name='uq_resume_result_projects_pair')
    )
    op.create_index(op.f('ix_resume_result_projects_project_id'), 'resume_result_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_resume_result_projects_resume_result_id'), 'resume_result_projects', ['resume_result_id'], unique=False)
    op.create_table('resume_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_result_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('section_type', sa.Text(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_result_id'], ['resume_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_sections_project_id'), 'resume_sections', ['project_id'], unique=False)
    op.create_index(op.f('ix_resume_sections_resume_result_id'), 'resume_sections', ['resume_result_id'], unique=False)
    op.create_index(op.f('ix_resume_sections_section_type'), 'resume_sections', ['section_type'], unique=False)
    op.create_table('resume_section_evidences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_section_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_section_id'], ['resume_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_section_id', 'evidence_id', name='uq_resume_section_evidences_pair')
    )
    op.create_index(op.f('ix_resume_section_evidences_evidence_id'), 'resume_section_evidences', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_resume_section_evidences_resume_section_id'), 'resume_section_evidences', ['resume_section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_section_evidences_resume_section_id'), table_name='resume_section_evidences')
    op.drop_index(op.f('ix_resume_section_evidences_evidence_id'), table_name='resume_section_evidences')
    op.drop_table('resume_section_evidences')
    op.drop_index(op.f('ix_resume_sections_section_type'), table_name='resume_sections')
    op.drop_index(op.f('ix_resume_sections_resume_result_id'), table_name='resume_sections')
    op.drop_index(op.f('ix_resume_sections_project_id'), table_name='resume_sections')
    op.drop_table('resume_sections')
    op.drop_index(op.f('ix_resume_result_projects_resume_result_id'), table_name='resume_result_projects')
    op.drop_index(op.f('ix_resume_result_projects_project_id'), table_name='resume_result_projects')
    op.drop_table('resume_result_projects')
    op.drop_index(op.f('ix_recommendation_evidences_recommended_project_id'), table_name='recommendation_evidences')
    op.drop_index(op.f('ix_recommendation_evidences_evidence_id'), table_name='recommendation_evidences')
    op.drop_table('recommendation_evidences')
    op.drop_index(op.f('ix_project_suggestions_resume_result_id'), table_name='project_suggestions')
    op.drop_table('project_suggestions')
    op.drop_index(op.f('ix_resume_results_user_id'), table_name='resume_results')
    op.drop_index(op.f('ix_resume_results_job_posting_id'), table_name='resume_results')
    op.drop_index(op.f('ix_resume_results_analysis_result_id'), table_name='resume_results')
    op.drop_table('resume_results')
    op.drop_index(op.f('ix_recommended_projects_project_id'), table_name='recommended_projects')
    op.drop_index(op.f('ix_recommended_projects_analysis_result_id'), table_name='recommended_projects')
    op.drop_table('recommended_projects')
    op.drop_index(op.f('ix_project_source_links_source_document_id'), table_name='project_source_links')
    op.drop_index(op.f('ix_project_source_links_project_id'), table_name='project_source_links')
    op.drop_table('project_source_links')
    op.drop_index(op.f('ix_evidences_source_type'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_source_document_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_project_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_job_posting_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_source_documents_portfolio_source_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_document_type'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_job_posting_attachments_status'), table_name='job_posting_attachments')
    op.drop_index(op.f('ix_job_posting_attachments_job_posting_id'), table_name='job_posting_attachments')
    op.drop_table('job_posting_attachments')
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_job_posting_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_portfolio_sources_user_id'), table_name='portfolio_sources')
    op.drop_index(op.f('ix_portfolio_sources_status'), table_name='portfolio_sources')
    op.drop_index(op.f('ix_portfolio_sources_source_type'), table_name='portfolio_sources')
    op.drop_table('portfolio_sources')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_job_postings_user_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_async_jobs_user_id'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_status'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_job_type'), table_name='async_jobs')
    op.drop_table('async_jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
